### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by Ovyerus**
This allows people to use node-shlex in their TypeScript projects without having to make their own definitions.

It might seem silly that this is so small, but it's what this library exposes publicly, and it just makes it easier for people in the future.

### CODE REVIEW

**Comment by rgov** [comment]
Thanks for this contribution. Could you please make sure that every file ends with a newline character?

**Comment by Ovyerus** [comment]
Fixed 👍

**Comment by rgov** [comment]
Thank you for resolving that quickly. I'm not sure whether it's necessary to have an additional test that TypeScript support is working, but if you feel it is, please feel free to contribute it.

**Comment by Ovyerus** [comment]
I did add a simple `test.ts` which doesn't run, but exists to make sure that TypeScript behaves as expected error wise (not compiling when wrong arguments, compiling when right arguments)

**Comment by rgov** [comment]
Published in version 1.0.3.

> I did add a simple `test.ts`...

My mistake, I missed it. How does one run it?

**Comment by Ovyerus** [comment]
It can be run with `ts-node` or compiled with `tsc` and then run (both of which weren't added to the package file), but they won't run properly if at all, because it contains two intentionally "bad" statements which disobey the given types, just to make sure it's working properly.

**Pull request merged**
